### ISSUE TITLE
ViewPage的图片多次点击放大缩小的时候就直接退出了

### ISSUE THREAD

**Issue by xinghedazhan** [QianFanYun/View-Images-and-Animations#1]

**Comment by TokenYc** [comment]
= =应该是触发了单击退出事件吧

**Comment by xinghedazhan** [comment]
photoView.setOnPhotoTapListener(new PhotoViewAttacher.OnPhotoTapListener() {
                @Override
                public void onPhotoTap(View view, float x, float y) {
//                    finish();
                }

```
            @Override
            public void onOutsidePhotoTap() {
```

//                    finish();
                }
            });
finish注销掉就可以了

**Comment by TokenYc** [comment]
这个并不是bug哦，是设计成单击退出的。很多主流应用都是这样滴。

**Comment by xinghedazhan** [comment]
哦哦，明白了
