### ISSUE TITLE
GlideImageLoader貌似没必要设置成单例模式，直接一个类调用静态方法就好

### ISSUE THREAD

**Issue by xinghedazhan** [QianFanYun/View-Images-and-Animations#3]

**Comment by TokenYc** [comment]
这里使用单例模式而不是静态方法是因为：GlideImageLoader继承于ImageLoader这个抽象类，实现了里面的加载图片的方法。静态方法不能在抽象类中使用，所以不使用静态方法。
这里使用ImageLoader抽象类是方便以后更换图片加载库，并且更加符合面向对象编程。
@xinghedazhan

**Comment by xinghedazhan** [comment]
以后换图片库的时候还要全项目改图片加载的名字？感觉不如直接在GlideImageLoader的方法里面修改方法实现来的方便

**Comment by TokenYc** [comment]
我把原来的抽象类ImageLoader改成了AImageLoader，GlideImageLoader改成了ImageLoader。这里用静态方法可以省去getInstance，会方便些，但是考虑到静态方法的一些弊端和更符合面向对象的写法，我还是用单例了。静态方法当然也是很可行的= =
